# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hORhIsUmbawG_ZsWrL8Zryo0irPZpf7R
"""

import os
import time
import shutil
import pathlib
import itertools
from PIL import Image

import cv2
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_style('darkgrid')
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam, Adamax
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Activation, Dropout, BatchNormalization
from tensorflow.keras import regularizers


import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image
import timm

import warnings
warnings.filterwarnings("ignore")

print ('modules loaded')

DATA_TYPE = 'data2'


if DATA_TYPE == 'data2':

    DATA_PATH = os.path.join('/kaggle/input', 'asl-alphabet','asl_alphabet_train','asl_alphabet_train')

elif DATA_TYPE == 'data3':

    DATA_PATH = os.path.join('/kaggle/input', 'unified-data','unified_data','unified_data','unified_data')

else:

    raise ValueError(f"Data {DATA_TYPE} not found.")



# elif DATA_TYPE == 'data1': # No considerado

#     DATA_PATH = os.path.join('..', '..', 'data', 'webcam_data','unified_data')